name: hexlet-check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: make install
      - run: make lint
